//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ProcessHacker.rc
//
#define PHAPP_IDR_RT_MANIFEST                 1
#define PHAPP_IDI_PROCESSHACKER               101
#define PHAPP_IDR_MAINWND                     102
#define PHAPP_IDR_MAINWND_ACCEL               102
#define PHAPP_IDD_PROCGENERAL                 103
#define PHAPP_IDD_PROCMODULES                 104
#define PHAPP_IDD_PROCTHREADS                 105
#define PHAPP_IDD_PROCHANDLES                 106
#define PHAPP_IDD_PROCENVIRONMENT             107
#define PHAPP_IDD_THRDSTACK                   108
#define PHAPP_IDR_THREAD                      110
#define PHAPP_IDR_HANDLE                      111
#define PHAPP_IDR_MODULE                      112
#define PHAPP_IDC_CPU                         112
#define PHAPP_IDC_PRIVATEBYTES                113
#define PHAPP_IDC_IO                          114
#define PHAPP_IDB_CROSS                       117
#define PHAPP_IDB_TICK                        118
#define PHAPP_IDC_PHYSICAL                    119
#define PHAPP_IDR_COMPUTER                    120
#define PHAPP_IDC_MEMORY                      120
#define PHAPP_IDD_ABOUT                       121
#define PHAPP_IDC_NEWOBJECTS                  121
#define PHAPP_IDC_REMOVEDOBJECTS              122
#define PHAPP_IDR_PROCESS                     123
#define PHAPP_IDC_CPUUSER                     123
#define PHAPP_IDR_SERVICE                     124
#define PHAPP_IDC_CPUKERNEL                   124
#define PHAPP_IDC_IORO                        125
#define PHAPP_IDD_SRVLIST                     125
#define PHAPP_IDD_SRVGENERAL                  126
#define PHAPP_IDC_IOW                         126
#define PHAPP_IDD_HNDLGENERAL                 128
#define PHAPP_IDD_INFORMATION                 129
#define PHAPP_IDD_FINDOBJECTS                 130
#define PHAPP_IDD_OBJTOKEN                    131
#define PHAPP_ID_PLUGIN_MENU_ITEM             131
#define PHAPP_ID_SHOWCONTEXTMENU              132
#define PHAPP_IDR_PRIVILEGE                   133
#define PHAPP_IDC_SEPARATOR                   133
#define PHAPP_IDR_FINDOBJ                     134
#define PHAPP_IDC_COMMIT                      134
#define PHAPP_IDD_HIDDENPROCESSES             135
#define PHAPP_ID_TRAYICONS_REGISTERED         135
#define PHAPP_IDD_RUNAS                       136
#define PHAPP_ID_COPY_CELL                    136
#define PHAPP_IDD_PROGRESS                    137
#define PHAPP_IDD_PAGEFILES                   138
#define PHAPP_IDD_TOKGENERAL                  139
#define PHAPP_IDD_TOKADVANCED                 140
#define PHAPP_IDD_OBJJOB                      141
#define PHAPP_IDD_OBJEVENT                    142
#define PHAPP_IDD_OBJMUTANT                   143
#define PHAPP_IDD_OBJSEMAPHORE                144
#define PHAPP_IDD_OBJTIMER                    145
#define PHAPP_IDD_JOBSTATISTICS               146
#define PHAPP_IDD_OBJEVENTPAIR                147
#define PHAPP_IDD_OBJSECTION                  148
#define PHAPP_IDD_AFFINITY                    149
#define PHAPP_IDD_SYSINFO                     150
#define PHAPP_IDR_USER                        151
#define PHAPP_IDD_EDITMESSAGE                 152
#define PHAPP_IDD_SESSION                     153
#define PHAPP_IDD_PROCMEMORY                  154
#define PHAPP_IDD_CHOOSE                      155
#define PHAPP_IDD_OPTGENERAL                  162
#define PHAPP_IDD_OPTHIGHLIGHTING             163
#define PHAPP_IDR_NETWORK                     164
#define PHAPP_IDD_CHOOSECOLUMNS               166
#define PHAPP_IDD_NETSTACK                    167
#define PHAPP_IDD_CREATESERVICE               168
#define PHAPP_IDD_PROCPERFORMANCE             169
#define PHAPP_IDD_PROCSTATISTICS              170
#define PHAPP_IDD_OPTADVANCED                 171
#define PHAPP_IDR_ICON                        173
#define PHAPP_IDD_GDIHANDLES                  175
#define PHAPP_IDD_LOG                         178
#define PHAPP_IDD_OPTSYMBOLS                  179
#define PHAPP_IDD_MEMEDIT                     180
#define PHAPP_IDR_MEMORY                      181
#define PHAPP_IDD_MEMPROTECT                  182
#define PHAPP_IDD_MEMRESULTS                  183
#define PHAPP_IDR_MEMFILTER                   184
#define PHAPP_IDD_MEMSTRING                   185
#define PHAPP_IDD_OPTGRAPHS                   186
#define PHAPP_IDD_PLUGINS                     187
#define PHAPP_IDD_HANDLESTATS                 188
#define PHAPP_IDD_PROCRECORD                  189
#define PHAPP_IDD_CHOOSEPROCESS               190
#define PHAPP_IDD_PROCSERVICES                191
#define PHAPP_IDI_PHAPPLICATION               191
#define PHAPP_IDI_COG                         192
#define PHAPP_IDD_SHADOWSESSION               193
#define PHAPP_IDI_PHAPPLICATIONGO             194
#define PHAPP_IDD_TOKCAPABILITIES             194
#define PHAPP_IDI_COGGO                       195
#define PHAPP_IDD_TOKATTRIBUTES               195
#define PHAPP_IDD_SYSINFO_CPU                 196
#define PHAPP_IDD_SYSINFO_CPUPANEL            197
#define PHAPP_IDD_SYSINFO_MEMPANEL            198
#define PHAPP_IDR_SYSINFO_ACCEL               198
#define PHAPP_IDD_SYSINFO_MEM                 199
#define PHAPP_IDD_SYSINFO_IO                  200
#define PHAPP_IDD_SYSINFO_IOPANEL             201
#define PHAPP_IDD_MEMLISTS                    202
#define PHAPP_IDR_EMPTYMEMLISTS               204
#define PHAPP_IDD_CONTAINER                   205
#define PHAPP_IDD_SYSINFO_MEMPANELXP          206
#define PHAPP_IDD_MINIINFO                    207
#define PHAPP_IDD_MINIINFO_LIST               210
#define PHAPP_IDR_MINIINFO                    211
#define PHAPP_IDR_MINIINFO_PROCESS            212
#define PHAPP_IDR_ENVIRONMENT                 214
#define PHAPP_IDD_MITIGATION                  215
#define PHAPP_IDI_PIN                         216
#define PHAPP_IDI_FOLDER                      217
#define PHAPP_IDI_PENCIL                      218
#define PHAPP_IDI_MAGNIFIER                   219
#define PHAPP_IDD_EDITENV                     221
#define PHAPP_IDC_TERMINATE                   1003
#define PHAPP_IDC_FILEICON                    1005
#define PHAPP_IDC_FILE                        1006
#define PHAPP_IDC_PROCESS                     1007
#define PHAPP_IDC_COMPANYNAME                 1009
#define PHAPP_IDC_VERSION                     1010
#define PHAPP_IDC_REFRESH                     1015
#define PHAPP_IDC_PERMISSIONS                 1018
#define PHAPP_IDC_FILENAME                    1020
#define PHAPP_IDC_CMDLINE                     1021
#define PHAPP_IDC_URL                         1021
#define PHAPP_IDC_RUNSELECTED                 1021
#define PHAPP_IDC_CURDIR                      1022
#define PHAPP_IDC_STARTED                     1023
#define PHAPP_IDC_ABOUT_NAME                  1024
#define PHAPP_IDC_PEBADDRESS                  1024
#define PHAPP_IDC_TERMINATED                  1024
#define PHAPP_IDC_PARENTPROCESS               1025
#define PHAPP_IDC_MITIGATION                  1026
#define PHAPP_IDC_PAUSE                       1027
#define PHAPP_IDC_PROTECTION                  1027
#define PHAPP_IDC_START                       1028
#define PHAPP_IDC_DESCRIPTION                 1029
#define PHAPP_IDC_TYPE                        1032
#define PHAPP_IDC_STARTTYPE                   1033
#define PHAPP_IDC_ADDRESS                     1033
#define PHAPP_IDC_IMPERSONATIONLEVEL          1033
#define PHAPP_IDC_ERRORCONTROL                1034
#define PHAPP_IDC_GRANTED_ACCESS              1034
#define PHAPP_IDC_TOKENLUID                   1034
#define PHAPP_IDC_GROUP                       1035
#define PHAPP_IDC_AUTHENTICATIONLUID          1035
#define PHAPP_IDC_BINARYPATH                  1036
#define PHAPP_IDC_MEMORYUSED                  1036
#define PHAPP_IDC_USERACCOUNT                 1037
#define PHAPP_IDC_MEMORYAVAILABLE             1037
#define PHAPP_IDC_PASSWORD                    1040
#define PHAPP_IDC_PASSWORDCHECK               1041
#define PHAPP_IDC_SERVICEDLL                  1042
#define PHAPP_IDC_NAME                        1044
#define PHAPP_IDC_REFERENCES                  1045
#define PHAPP_IDC_INTERNALNAME                1045
#define PHAPP_IDC_HANDLES                     1046
#define PHAPP_IDC_PROCESSTYPELABEL            1046
#define PHAPP_IDC_AUTHOR                      1046
#define PHAPP_IDC_PAGED                       1047
#define PHAPP_IDC_PROCESSTYPETEXT             1047
#define PHAPP_IDC_NONPAGED                    1048
#define PHAPP_IDC_TEXT                        1048
#define PHAPP_IDC_DIAGNOSTICS                 1049
#define PHAPP_IDC_FILTER                      1050
#define PHAPP_IDC_RESULTS                     1051
#define PHAPP_IDC_USER                        1052
#define PHAPP_IDC_USERSID                     1053
#define PHAPP_IDC_ADVANCED                    1054
#define PHAPP_IDC_OWNER                       1054
#define PHAPP_IDC_GROUPS                      1055
#define PHAPP_IDC_PRIMARYGROUP                1055
#define PHAPP_IDC_PRIVILEGES                  1056
#define PHAPP_IDC_VIRTUALIZATION              1056
#define PHAPP_IDC_SESSIONID                   1057
#define PHAPP_IDC_ELEVATED                    1058
#define PHAPP_IDC_VIRTUALIZED                 1059
#define PHAPP_IDC_SOURCENAME                  1059
#define PHAPP_IDC_PROPERTIES                  1060
#define PHAPP_IDC_SOURCELUID                  1060
#define PHAPP_IDC_APPCONTAINERSID             1060
#define PHAPP_IDC_LIST                        1061
#define PHAPP_IDC_PROCESSES                   1063
#define PHAPP_IDC_SCAN                        1064
#define PHAPP_IDC_SAVE                        1065
#define PHAPP_IDC_METHOD                      1067
#define PHAPP_IDC_INTRO                       1068
#define PHAPP_IDC_PROGRAM                     1069
#define PHAPP_IDC_BROWSE                      1070
#define PHAPP_IDC_USERNAME                    1071
#define PHAPP_IDC_SESSIONS                    1074
#define PHAPP_IDC_DESKTOPS                    1075
#define PHAPP_IDC_PROGRESS                    1076
#define PHAPP_IDC_PROGRESSTEXT                1077
#define PHAPP_IDC_LINKEDTOKEN                 1079
#define PHAPP_IDC_DISABLEALL                  1079
#define PHAPP_IDC_MOVEUP                      1079
#define PHAPP_IDC_CHANGE                      1079
#define PHAPP_IDC_CLEAR                       1079
#define PHAPP_IDC_GOTO                        1079
#define PHAPP_IDC_OPTIONS                     1079
#define PHAPP_IDC_DETAILS                     1079
#define PHAPP_IDC_ADD                         1079
#define PHAPP_IDC_FONT                        1079
#define PHAPP_IDC_INTEGRITY                   1079
#define PHAPP_IDC_MORE                        1079
#define PHAPP_IDC_VIEWMITIGATION              1080
#define PHAPP_IDC_VIEWPARENTPROCESS           1081
#define PHAPP_IDC_OPENFILENAME                1082
#define PHAPP_IDC_LIMITS                      1083
#define PHAPP_IDC_SIGNALED                    1084
#define PHAPP_IDC_SET                         1085
#define PHAPP_IDC_RESET                       1086
#define PHAPP_IDC_PULSE                       1087
#define PHAPP_IDC_COUNT                       1088
#define PHAPP_IDC_ABANDONED                   1089
#define PHAPP_IDC_CURRENTCOUNT                1090
#define PHAPP_IDC_MAXIMUMCOUNT                1091
#define PHAPP_IDC_ACQUIRE                     1092
#define PHAPP_IDC_RELEASE                     1093
#define PHAPP_IDC_CANCEL                      1094
#define PHAPP_IDC_OWNERLABEL                  1095
#define PHAPP_IDC_SETLOW                      1096
#define PHAPP_IDC_SETHIGH                     1097
#define PHAPP_IDC_SIZE_                       1098
#define PHAPP_IDC_CPU0                        1099
#define PHAPP_IDC_CPU1                        1100
#define PHAPP_IDC_CPU2                        1101
#define PHAPP_IDC_CPU3                        1102
#define PHAPP_IDC_CPU4                        1103
#define PHAPP_IDC_CPU5                        1104
#define PHAPP_IDC_CPU6                        1105
#define PHAPP_IDC_CPU7                        1106
#define PHAPP_IDC_CPU8                        1107
#define PHAPP_IDC_TITLE                       1107
#define PHAPP_IDC_CPU9                        1108
#define PHAPP_IDC_CPU10                       1109
#define PHAPP_IDC_TIMEOUT                     1109
#define PHAPP_IDC_CPU11                       1110
#define PHAPP_IDC_CPU12                       1111
#define PHAPP_IDC_STATE                       1111
#define PHAPP_IDC_CPU13                       1112
#define PHAPP_IDC_CLIENTNAME                  1112
#define PHAPP_IDC_CPU14                       1113
#define PHAPP_IDC_CLIENTADDRESS               1113
#define PHAPP_IDC_CPU15                       1114
#define PHAPP_IDC_CLIENTDISPLAY               1114
#define PHAPP_IDC_CPU16                       1115
#define PHAPP_IDC_CHOICE                      1115
#define PHAPP_IDC_CPU17                       1116
#define PHAPP_IDC_OPTION                      1116
#define PHAPP_IDC_CPU18                       1117
#define PHAPP_IDC_CHOICEUSER                  1117
#define PHAPP_IDC_CPU19                       1118
#define PHAPP_IDC_HIDEUNNAMEDHANDLES          1118
#define PHAPP_IDC_CPU20                       1119
#define PHAPP_IDC_CPU21                       1120
#define PHAPP_IDC_STARTMODULE                 1120
#define PHAPP_IDC_CPU22                       1121
#define PHAPP_IDC_OPENSTARTMODULE             1121
#define PHAPP_IDC_CPU23                       1122
#define PHAPP_IDC_KERNELTIME                  1122
#define PHAPP_IDC_CPU24                       1123
#define PHAPP_IDC_USERTIME                    1123
#define PHAPP_IDC_CPU25                       1124
#define PHAPP_IDC_CONTEXTSWITCHES             1124
#define PHAPP_IDC_CPU26                       1125
#define PHAPP_IDC_CYCLES                      1125
#define PHAPP_IDC_CPU27                       1126
#define PHAPP_IDC_PRIORITY                    1126
#define PHAPP_IDC_CPU28                       1127
#define PHAPP_IDC_BASEPRIORITY                1127
#define PHAPP_IDC_CPU29                       1128
#define PHAPP_IDC_IOPRIORITY                  1128
#define PHAPP_IDC_CPU30                       1129
#define PHAPP_IDC_PAGEPRIORITY                1129
#define PHAPP_IDC_CPU31                       1130
#define PHAPP_IDC_STATICBL1                   1130
#define PHAPP_IDC_STATICBL2                   1131
#define PHAPP_IDC_CPU32                       1131
#define PHAPP_IDC_STATICBL3                   1132
#define PHAPP_IDC_CPU33                       1132
#define PHAPP_IDC_STATICBL4                   1133
#define PHAPP_IDC_CPU34                       1133
#define PHAPP_IDC_STATICBL5                   1134
#define PHAPP_IDC_CPU35                       1134
#define PHAPP_IDC_STATICBL6                   1135
#define PHAPP_IDC_CPU36                       1135
#define PHAPP_IDC_STATICBL7                   1136
#define PHAPP_IDC_CPU37                       1136
#define PHAPP_IDC_STATICBL8                   1137
#define PHAPP_IDC_CPU38                       1137
#define PHAPP_IDC_STATICBL9                   1138
#define PHAPP_IDC_CPU39                       1138
#define PHAPP_IDC_STATICBL10                  1139
#define PHAPP_IDC_CPU40                       1139
#define PHAPP_IDC_STATICBL11                  1140
#define PHAPP_IDC_CPU41                       1140
#define PHAPP_IDC_CHOICESIMPLE                1141
#define PHAPP_IDC_CPU42                       1141
#define PHAPP_IDC_MESSAGE                     1142
#define PHAPP_IDC_CPU43                       1142
#define PHAPP_IDC_SEARCHENGINE                1143
#define PHAPP_IDC_CPU44                       1143
#define PHAPP_IDC_MAXSIZEUNIT                 1144
#define PHAPP_IDC_CPU45                       1144
#define PHAPP_IDC_ALLOWONLYONEINSTANCE        1145
#define PHAPP_IDC_CPU46                       1145
#define PHAPP_IDC_HIDEONCLOSE                 1146
#define PHAPP_IDC_CPU47                       1146
#define PHAPP_IDC_ENABLEWARNINGS              1147
#define PHAPP_IDC_HIDEONMINIMIZE              1147
#define PHAPP_IDC_CPU48                       1147
#define PHAPP_IDC_STARTHIDDEN                 1148
#define PHAPP_IDC_CPU49                       1148
#define PHAPP_IDC_ENABLEKERNELMODEDRIVER      1149
#define PHAPP_IDC_CPU50                       1149
#define PHAPP_IDC_CPU51                       1150
#define PHAPP_IDC_PEVIEWER                    1151
#define PHAPP_IDC_CPU52                       1151
#define PHAPP_IDC_CPU53                       1152
#define PHAPP_IDC_CPU54                       1153
#define PHAPP_IDC_CPU55                       1154
#define PHAPP_IDC_HIGHLIGHTINGDURATION        1155
#define PHAPP_IDC_CPU56                       1155
#define PHAPP_IDC_CPU57                       1156
#define PHAPP_IDC_ENABLEALL                   1157
#define PHAPP_IDC_CPU58                       1157
#define PHAPP_IDC_ZACTIVEPROCESSES_V          1158
#define PHAPP_IDC_CPU59                       1158
#define PHAPP_IDC_ZTOTALPROCESSES_V           1159
#define PHAPP_IDC_CPU60                       1159
#define PHAPP_IDC_ZTERMINATEDPROCESSES_V      1160
#define PHAPP_IDC_CPU61                       1160
#define PHAPP_IDC_ZUSERTIME_V                 1161
#define PHAPP_IDC_CPU62                       1161
#define PHAPP_IDC_ZKERNELTIME_V               1162
#define PHAPP_IDC_CPU63                       1162
#define PHAPP_IDC_ZUSERTIMEPERIOD_V           1163
#define PHAPP_IDC_ZKERNELTIMEPERIOD_V         1164
#define PHAPP_IDC_ZPAGEFAULTS_V               1165
#define PHAPP_IDC_ZPEAKPROCESSUSAGE_V         1166
#define PHAPP_IDC_ZPEAKJOBUSAGE_V             1167
#define PHAPP_IDC_ZIOREADS_V                  1168
#define PHAPP_IDC_ZIOREADBYTES_V              1169
#define PHAPP_IDC_ZIOWRITES_V                 1170
#define PHAPP_IDC_ZIOWRITEBYTES_V             1171
#define PHAPP_IDC_ZIOOTHER_V                  1172
#define PHAPP_IDC_ZIOOTHERBYTES_V             1173
#define PHAPP_IDC_MOVEDOWN                    1176
#define PHAPP_IDC_DISPLAYNAME                 1179
#define PHAPP_IDC_ZPRIORITY_V                 1181
#define PHAPP_IDC_ZCYCLES_V                   1182
#define PHAPP_IDC_ZTOTALTIME_V                1185
#define PHAPP_IDC_ZPRIVATEBYTES_V             1186
#define PHAPP_IDC_ZWORKINGSET_V               1187
#define PHAPP_IDC_ZPEAKWORKINGSET_V           1188
#define PHAPP_IDC_ZVIRTUALSIZE_V              1189
#define PHAPP_IDC_ZPEAKVIRTUALSIZE_V          1190
#define PHAPP_IDC_ZPEAKPRIVATEBYTES_V         1191
#define PHAPP_IDC_ZPAGEPRIORITY_V             1192
#define PHAPP_IDC_ZIOPRIORITY_V               1194
#define PHAPP_IDC_ZHANDLES_V                  1195
#define PHAPP_IDC_ZGDIHANDLES_V               1196
#define PHAPP_IDC_ZOTHERDELTA_V               1196
#define PHAPP_IDC_ZUSERHANDLES_V              1197
#define PHAPP_IDC_ZOTHER_V                    1197
#define PHAPP_IDC_GROUPCPU                    1198
#define PHAPP_IDC_GROUPPRIVATEBYTES           1199
#define PHAPP_IDC_GROUPIO                     1200
#define PHAPP_IDC_ONEGRAPHPERCPU              1202
#define PHAPP_IDC_ALWAYSONTOP                 1203
#define PHAPP_IDC_COPY                        1206
#define PHAPP_IDC_INACTIVE                    1207
#define PHAPP_IDC_ACTIVE                      1208
#define PHAPP_IDC_SHOW                        1209
#define PHAPP_IDC_HIDE                        1210
#define PHAPP_IDC_REPLACETASKMANAGER          1211
#define PHAPP_IDC_AUTOSCROLL                  1215
#define PHAPP_IDC_UNDECORATESYMBOLS           1216
#define PHAPP_IDC_DBGHELPPATH                 1217
#define PHAPP_IDC_DBGHELPSEARCHPATH           1218
#define PHAPP_IDC_COLLAPSESERVICES            1219
#define PHAPP_IDC_ICONSINGLECLICK             1220
#define PHAPP_IDC_DESKTOP                     1221
#define PHAPP_IDC_REREAD                      1224
#define PHAPP_IDC_WRITE                       1225
#define PHAPP_IDC_VALUE                       1230
#define PHAPP_IDC_DELAYEDSTART                1234
#define PHAPP_IDC_MINIMUMLENGTH               1236
#define PHAPP_IDC_DETECTUNICODE               1237
#define PHAPP_IDC_PRIVATE                     1238
#define PHAPP_IDC_IMAGE                       1239
#define PHAPP_IDC_MAPPED                      1240
#define PHAPP_IDC_STRINGS                     1242
#define PHAPP_IDC_SHOWTEXT                    1245
#define PHAPP_IDC_ICONPROCESSES               1248
#define PHAPP_IDC_CLEANUP                     1251
#define PHAPP_IDC_ENABLESTAGE2                1253
#define PHAPP_IDC_TOGGLEELEVATION             1254
#define PHAPP_IDC_ENABLEPLUGINS               1258
#define PHAPP_IDC_PARENT                      1263
#define PHAPP_IDC_PROCESSNAME                 1264
#define PHAPP_IDC_SERVICES_LAYOUT             1266
#define PHAPP_IDC_LINK_SF                     1267
#define PHAPP_IDC_CREDITS                     1270
#define PHAPP_IDC_ENABLENETWORKRESOLVE        1271
#define PHAPP_IDC_LOGONTIME                   1272
#define PHAPP_IDC_ZPEAKHANDLES_V              1273
#define PHAPP_IDC_PROPAGATECPUUSAGE           1274
#define PHAPP_IDC_SHIFT                       1274
#define PHAPP_IDC_USEOLDCOLORS                1274
#define PHAPP_IDC_ICONTOGGLESVISIBILITY       1274
#define PHAPP_IDC_OPENURL                     1279
#define PHAPP_IDC_COMPANYNAME_LINK            1279
#define PHAPP_IDC_SAMPLECOUNT                 1280
#define PHAPP_IDC_SAMPLECOUNTLABEL            1281
#define PHAPP_IDC_DISABLE                     1282
#define PHAPP_IDC_VIRTUALKEY                  1283
#define PHAPP_IDC_CTRL                        1284
#define PHAPP_IDC_ALT                         1285
#define PHAPP_IDC_CONNECTTIME                 1286
#define PHAPP_IDC_DISCONNECTTIME              1287
#define PHAPP_IDC_LASTINPUTTIME               1288
#define PHAPP_IDC_ZPRIVATEWS_V                1289
#define PHAPP_IDC_ZSHAREABLEWS_V              1290
#define PHAPP_IDC_ZSHAREDWS_V                 1291
#define PHAPP_IDC_ENABLEINSTANTTOOLTIPS       1292
#define PHAPP_IDC_ENABLECYCLECPUUSAGE         1293
#define PHAPP_IDC_IDEALPROCESSOR              1294
#define PHAPP_IDC_STATICBL12                  1295
#define PHAPP_IDC_BASICINFORMATION            1296
#define PHAPP_IDC_INSTRUCTION                 1298
#define PHAPP_IDC_CPUNAME                     1299
#define PHAPP_IDC_LAYOUT                      1300
#define PHAPP_IDC_UTILIZATION                 1301
#define PHAPP_IDC_SPEED                       1302
#define PHAPP_IDC_ZPROCESSES_V                1303
#define PHAPP_IDC_ZTHREADS_V                  1304
#define PHAPP_IDC_ZCONTEXTSWITCHESDELTA_V     1307
#define PHAPP_IDC_ZINTERRUPTSDELTA_V          1308
#define PHAPP_IDC_ZDPCSDELTA_V                1309
#define PHAPP_IDC_ZSYSTEMCALLSDELTA_V         1310
#define PHAPP_IDC_GRAPH_LAYOUT                1311
#define PHAPP_IDC_TOTALPHYSICAL               1312
#define PHAPP_IDC_ZCOMMITCURRENT_V            1314
#define PHAPP_IDC_ZCOMMITPEAK_V               1315
#define PHAPP_IDC_ZCOMMITLIMIT_V              1316
#define PHAPP_IDC_ZPHYSICALCURRENT_V          1317
#define PHAPP_IDC_ZPHYSICALTOTAL_V            1318
#define PHAPP_IDC_ZPHYSICALCACHEWS_V          1319
#define PHAPP_IDC_ZPHYSICALKERNELWS_V         1320
#define PHAPP_IDC_ZPHYSICALDRIVERWS_V         1321
#define PHAPP_IDC_ZPAGEDWORKINGSET_V          1322
#define PHAPP_IDC_ZPAGEDVIRTUALSIZE_V         1323
#define PHAPP_IDC_ZPAGEDLIMIT_V               1324
#define PHAPP_IDC_ZPAGEDALLOCSDELTA_V         1325
#define PHAPP_IDC_ZPAGEDFREESDELTA_V          1326
#define PHAPP_IDC_ZNONPAGEDUSAGE_V            1327
#define PHAPP_IDC_ZNONPAGEDLIMIT_V            1328
#define PHAPP_IDC_ZNONPAGEDALLOCSDELTA_V      1329
#define PHAPP_IDC_ZNONPAGEDFREESDELTA_V       1330
#define PHAPP_IDC_ZPHYSICALRESERVED_V         1331
#define PHAPP_IDC_ZLISTZEROED_V               1332
#define PHAPP_IDC_ZLISTFREE_V                 1333
#define PHAPP_IDC_ZLISTMODIFIED_V             1334
#define PHAPP_IDC_ZLISTMODIFIEDNOWRITE_V      1335
#define PHAPP_IDC_ZLISTSTANDBY_V              1337
#define PHAPP_IDC_COMMIT_L                    1339
#define PHAPP_IDC_PHYSICAL_L                  1340
#define PHAPP_IDC_ZUPTIME_V                   1341
#define PHAPP_IDC_ZOTHERBYTESDELTA_V          1342
#define PHAPP_IDC_ZREADSDELTA_V               1343
#define PHAPP_IDC_ZREADBYTESDELTA_V           1344
#define PHAPP_IDC_ZWRITESDELTA_V              1345
#define PHAPP_IDC_ZLISTSTANDBY0_V             1346
#define PHAPP_IDC_ZWRITEBYTESDELTA_V          1346
#define PHAPP_IDC_ZLISTSTANDBY1_V             1347
#define PHAPP_IDC_ZREADS_V                    1347
#define PHAPP_IDC_ZLISTSTANDBY2_V             1348
#define PHAPP_IDC_ZREADBYTES_V                1348
#define PHAPP_IDC_ZLISTSTANDBY3_V             1349
#define PHAPP_IDC_ZWRITES_V                   1349
#define PHAPP_IDC_ZLISTBAD_V                  1350
#define PHAPP_IDC_ZWRITEBYTES_V               1350
#define PHAPP_IDC_ZLISTREPURPOSED_V           1351
#define PHAPP_IDC_ZOTHERBYTES_V               1351
#define PHAPP_IDC_ZLISTREPURPOSED0_V          1352
#define PHAPP_IDC_ZLISTREPURPOSED1_V          1353
#define PHAPP_IDC_ZLISTREPURPOSED2_V          1354
#define PHAPP_IDC_ZLISTREPURPOSED3_V          1355
#define PHAPP_IDC_ZLISTREPURPOSED4_V          1356
#define PHAPP_IDC_ZLISTREPURPOSED5_V          1357
#define PHAPP_IDC_ZLISTREPURPOSED6_V          1358
#define PHAPP_IDC_ZLISTREPURPOSED7_V          1359
#define PHAPP_IDC_EMPTY                       1360
#define PHAPP_IDC_SAMPLECOUNTAUTOMATIC        1361
#define PHAPP_IDC_SHOWCOMMITINSUMMARY         1361
#define PHAPP_IDC_ZLISTSTANDBY4_V             1364
#define PHAPP_IDC_ZLISTSTANDBY5_V             1365
#define PHAPP_IDC_SELECTALL                   1365
#define PHAPP_IDC_ZLISTSTANDBY6_V             1366
#define PHAPP_IDC_DESELECTALL                 1366
#define PHAPP_IDC_ZLISTSTANDBY7_V             1367
#define PHAPP_IDC_INSPECT                     1367
#define PHAPP_IDC_ZPAGINGPAGEFAULTSDELTA_V    1368
#define PHAPP_IDC_HIDEFREEREGIONS             1368
#define PHAPP_IDC_ZPAGINGPAGEREADSDELTA_V     1369
#define PHAPP_IDC_BYTESPERROW                 1369
#define PHAPP_IDC_ZPAGINGPAGEFILEWRITESDELTA_V 1370
#define PHAPP_IDC_PIN                         1370
#define PHAPP_IDC_ZPAGINGMAPPEDWRITESDELTA_V  1371
#define PHAPP_IDC_ZLISTMODIFIEDPAGEFILE_V     1373
#define PHAPP_IDC_SECTION                     1375
#define PHAPP_IDC_REGEX                       1377
#define PHAPP_IDC_DESCRIPTIONLABEL            1378
#define PHAPP_IDC_STARTATLOGON                1380
#define PHAPP_IDC_VIEWCOMMANDLINE             1381
#define PHAPP_IDC_DELETE                      1382
#define PHAPP_IDC_EDIT                        1383
#define PHAPP_IDC_NEW                         1384
#define PHAPP_ID_MAINWND_PROCESSTL            2001
#define PHAPP_ID_MAINWND_SERVICETL            2002
#define PHAPP_ID_MAINWND_NETWORKTL            2003
#define PHAPP_ID_MAINWND_PROCESSLV            2004
#define PHAPP_ID_HACKER_EXIT                  40001
#define PHAPP_ID_PROCESS_PROPERTIES           40006
#define PHAPP_ID_PROCESS_TERMINATE            40007
#define PHAPP_ID_PROCESS_SUSPEND              40008
#define PHAPP_ID_PROCESS_RESUME               40009
#define PHAPP_ID_HACKER_SAVE                  40010
#define PHAPP_ID_THREAD_TERMINATE             40011
#define PHAPP_ID_THREAD_SUSPEND               40012
#define PHAPP_ID_THREAD_RESUME                40013
#define PHAPP_ID_THREAD_PERMISSIONS           40015
#define PHAPP_ID_THREAD_TOKEN                 40016
#define PHAPP_ID_ANALYZE_WAIT                 40018
#define PHAPP_ID_PRIORITY_TIMECRITICAL        40020
#define PHAPP_ID_PRIORITY_HIGHEST             40021
#define PHAPP_ID_PRIORITY_ABOVENORMAL         40022
#define PHAPP_ID_PRIORITY_NORMAL              40023
#define PHAPP_ID_PRIORITY_BELOWNORMAL         40024
#define PHAPP_ID_PRIORITY_LOWEST              40025
#define PHAPP_ID_PRIORITY_IDLE                40026
#define PHAPP_ID_IOPRIORITY_VERYLOW           40028
#define PHAPP_ID_IOPRIORITY_LOW               40029
#define PHAPP_ID_IOPRIORITY_NORMAL            40030
#define PHAPP_ID_IOPRIORITY_HIGH              40031
#define PHAPP_ID_PROCESS_RESTART              40032
#define PHAPP_ID_PROCESS_VIRTUALIZATION       40034
#define PHAPP_ID_PROCESS_AFFINITY             40035
#define PHAPP_ID_PROCESS_CREATEDUMPFILE       40036
#define PHAPP_ID_MISCELLANEOUS_DETACHFROMDEBUGGER 40039
#define PHAPP_ID_MISCELLANEOUS_HEAPS          40040
#define PHAPP_ID_MISCELLANEOUS_INJECTDLL      40041
#define PHAPP_ID_PRIORITY_REALTIME            40048
#define PHAPP_ID_PRIORITY_HIGH                40049
#define PHAPP_ID_WINDOW_BRINGTOFRONT          40055
#define PHAPP_ID_WINDOW_RESTORE               40056
#define PHAPP_ID_WINDOW_MINIMIZE              40057
#define PHAPP_ID_WINDOW_MAXIMIZE              40058
#define PHAPP_ID_WINDOW_CLOSE                 40059
#define PHAPP_ID_PROCESS_SEARCHONLINE         40060
#define PHAPP_ID_HANDLE_CLOSE                 40061
#define PHAPP_ID_HANDLE_PROTECTED             40062
#define PHAPP_ID_HANDLE_INHERIT               40063
#define PHAPP_ID_HANDLE_PROPERTIES            40064
#define PHAPP_ID_MODULE_UNLOAD                40066
#define PHAPP_ID_MODULE_PROPERTIES            40068
#define PHAPP_ID_PROCESS_TERMINATETREE        40069
#define PHAPP_ID_THREAD_INSPECT               40075
#define PHAPP_ID_HACKER_RUN                   40076
#define PHAPP_ID_HACKER_RUNASADMINISTRATOR    40077
#define PHAPP_ID_HACKER_RUNAS                 40078
#define PHAPP_ID_HACKER_SHOWDETAILSFORALLPROCESSES 40079
#define PHAPP_ID_HACKER_FINDHANDLESORDLLS     40082
#define PHAPP_ID_HACKER_OPTIONS               40083
#define PHAPP_ID_VIEW_SYSTEMINFORMATION       40091
#define PHAPP_ID_TRAYICONS_CPUHISTORY         40093
#define PHAPP_ID_TRAYICONS_CPUUSAGE           40094
#define PHAPP_ID_TRAYICONS_COMMITHISTORY      40096
#define PHAPP_ID_TRAYICONS_PHYSICALMEMORYHISTORY 40097
#define PHAPP_ID_VIEW_REFRESH                 40098
#define PHAPP_ID_TOOLS_CREATESERVICE          40101
#define PHAPP_ID_TOOLS_HIDDENPROCESSES        40102
#define PHAPP_ID_TOOLS_INSPECTEXECUTABLEFILE  40103
#define PHAPP_ID_HELP_LOG                     40104
#define PHAPP_ID_HELP_DONATE                  40105
#define PHAPP_ID_HELP_ABOUT                   40106
#define PHAPP_ID_SERVICE_GOTOPROCESS          40107
#define PHAPP_ID_SERVICE_START                40108
#define PHAPP_ID_SERVICE_CONTINUE             40109
#define PHAPP_ID_SERVICE_PAUSE                40110
#define PHAPP_ID_SERVICE_STOP                 40111
#define PHAPP_ID_SERVICE_DELETE               40112
#define PHAPP_ID_SERVICE_PROPERTIES           40113
#define PHAPP_ID_SERVICE_OPENKEY              40114
#define PHAPP_ID_PRIVILEGE_ENABLE             40116
#define PHAPP_ID_PRIVILEGE_DISABLE            40117
#define PHAPP_ID_PRIVILEGE_REMOVE             40118
#define PHAPP_ID_OBJECT_CLOSE                 40119
#define PHAPP_ID_OBJECT_PROPERTIES            40120
#define PHAPP_ID_HELP_DEBUGCONSOLE            40122
#define PHAPP_ID_MODULE_SEARCHONLINE          40125
#define PHAPP_ID_TOOLS_PAGEFILES              40126
#define PHAPP_ID_USER_DISCONNECT              40127
#define PHAPP_ID_USER_LOGOFF                  40128
#define PHAPP_ID_USER_SENDMESSAGE             40129
#define PHAPP_ID_USER_PROPERTIES              40130
#define PHAPP_ID_USERS_DUMMY                  40131
#define PHAPP_ID_MODULE_INSPECT               40132
#define PHAPP_ID_PROCESS_DEBUG                40133
#define PHAPP_ID_USER_CONNECT                 40138
#define PHAPP_ID_NETWORK_GOTOPROCESS          40139
#define PHAPP_ID_NETWORK_CLOSE                40140
#define PHAPP_ID_OPACITY_10                   40142
#define PHAPP_ID_OPACITY_20                   40143
#define PHAPP_ID_OPACITY_30                   40144
#define PHAPP_ID_OPACITY_40                   40145
#define PHAPP_ID_OPACITY_50                   40146
#define PHAPP_ID_OPACITY_60                   40147
#define PHAPP_ID_OPACITY_70                   40148
#define PHAPP_ID_OPACITY_80                   40149
#define PHAPP_ID_OPACITY_90                   40150
#define PHAPP_ID_OPACITY_OPAQUE               40151
#define PHAPP_ID_VIEW_ALWAYSONTOP             40153
#define PHAPP_ID_UPDATEINTERVAL_FAST          40155
#define PHAPP_ID_UPDATEINTERVAL_NORMAL        40156
#define PHAPP_ID_UPDATEINTERVAL_BELOWNORMAL   40157
#define PHAPP_ID_UPDATEINTERVAL_SLOW          40158
#define PHAPP_ID_UPDATEINTERVAL_VERYSLOW      40159
#define PHAPP_ID_COMPUTER_LOCK                40160
#define PHAPP_ID_COMPUTER_LOGOFF              40161
#define PHAPP_ID_COMPUTER_SLEEP               40162
#define PHAPP_ID_COMPUTER_HIBERNATE           40163
#define PHAPP_ID_COMPUTER_RESTART             40164
#define PHAPP_ID_COMPUTER_SHUTDOWN            40165
#define PHAPP_ID_NETWORK_VIEWSTACK            40167
#define PHAPP_ID_TRAYICONS_IOHISTORY          40168
#define PHAPP_ID_ICON_EXIT                    40169
#define PHAPP_ID_ICON_SHOWHIDEPROCESSHACKER   40171
#define PHAPP_ID_ICON_SYSTEMINFORMATION       40172
#define PHAPP_ID_PROCESSES_DUMMY              40177
#define PHAPP_ID_NOTIFICATIONS_ENABLEALL      40178
#define PHAPP_ID_NOTIFICATIONS_DISABLEALL     40179
#define PHAPP_ID_NOTIFICATIONS_NEWPROCESSES   40180
#define PHAPP_ID_NOTIFICATIONS_TERMINATEDPROCESSES 40181
#define PHAPP_ID_NOTIFICATIONS_NEWSERVICES    40182
#define PHAPP_ID_NOTIFICATIONS_STARTEDSERVICES 40183
#define PHAPP_ID_NOTIFICATIONS_STOPPEDSERVICES 40184
#define PHAPP_ID_NOTIFICATIONS_DELETEDSERVICES 40185
#define PHAPP_ID_MISCELLANEOUS_GDIHANDLES     40188
#define PHAPP_ID_ESC_EXIT                     40190
#define PHAPP_ID_PROCESS_COPY                 40194
#define PHAPP_ID_THREAD_COPY                  40195
#define PHAPP_ID_PRIVILEGE_COPY               40196
#define PHAPP_ID_NETWORK_COPY                 40197
#define PHAPP_ID_SERVICE_COPY                 40198
#define PHAPP_ID_MODULE_COPY                  40199
#define PHAPP_ID_HANDLE_COPY                  40200
#define PHAPP_ID_OBJECT_COPY                  40201
#define PHAPP_ID_MEMORY_SAVE                  40208
#define PHAPP_ID_MEMORY_CHANGEPROTECTION      40209
#define PHAPP_ID_MEMORY_FREE                  40210
#define PHAPP_ID_MEMORY_DECOMMIT              40211
#define PHAPP_ID_MEMORY_COPY                  40213
#define PHAPP_ID_MEMORY_READWRITEMEMORY       40214
#define PHAPP_ID_MEMORY_READWRITEADDRESS      40215
#define PHAPP_ID_FILTER_CONTAINS              40216
#define PHAPP_ID_FILTER_CONTAINS_CASEINSENSITIVE 40218
#define PHAPP_ID_FILTER_REGEX                 40219
#define PHAPP_ID_FILTER_REGEX_CASEINSENSITIVE 40221
#define PHAPP_ID_TAB_NEXT                     40223
#define PHAPP_ID_TAB_PREV                     40224
#define PHAPP_ID_MISCELLANEOUS_RUNAS          40229
#define PHAPP_ID_MISCELLANEOUS_RUNASTHISUSER  40230
#define PHAPP_ID_HACKER_PLUGINS               40231
#define PHAPP_ID_VIEW_HIDEPROCESSESFROMOTHERUSERS 40232
#define PHAPP_ID_THREAD_AFFINITY              40233
#define PHAPP_ID_VIEW_HIDESIGNEDPROCESSES     40234
#define PHAPP_ID_VIEW_UPDATEAUTOMATICALLY     40235
#define PHAPP_ID_HACKER_RUNASLIMITEDUSER      40236
#define PHAPP_ID_USER_REMOTECONTROL           40237
#define PHAPP_ID_PAGEPRIORITY_NORMAL          40239
#define PHAPP_ID_PAGEPRIORITY_BELOWNORMAL     40240
#define PHAPP_ID_PAGEPRIORITY_MEDIUM          40241
#define PHAPP_ID_PAGEPRIORITY_LOW             40242
#define PHAPP_ID_PAGEPRIORITY_VERYLOW         40243
#define PHAPP_ID_VIEW_SHOWCPUBELOW001         40246
#define PHAPP_ID_MODULE_OPENFILELOCATION      40247
#define PHAPP_ID_PROCESS_OPENFILELOCATION     40248
#define PHAPP_ID_MISCELLANEOUS_REDUCEWORKINGSET 40249
#define PHAPP_ID_EMPTY_EMPTYWORKINGSETS       40250
#define PHAPP_ID_EMPTY_EMPTYMODIFIEDPAGELIST  40251
#define PHAPP_ID_EMPTY_EMPTYSTANDBYLIST       40252
#define PHAPP_ID_EMPTY_EMPTYPRIORITY0STANDBYLIST 40253
#define PHAPP_IDC_BACK                        40255
#define PHAPP_ID_DIGIT1                       40263
#define PHAPP_ID_DIGIT2                       40264
#define PHAPP_ID_DIGIT3                       40265
#define PHAPP_ID_DIGIT4                       40266
#define PHAPP_ID_DIGIT5                       40267
#define PHAPP_ID_DIGIT6                       40268
#define PHAPP_ID_DIGIT7                       40269
#define PHAPP_ID_DIGIT8                       40270
#define PHAPP_ID_DIGIT9                       40271
#define PHAPP_ID_VIEW_HIDEDRIVERSERVICES      40273
#define PHAPP_ID_VIEW_SECTIONPLACEHOLDER      40274
#define PHAPP_ID_VIEW_SCROLLTONEWPROCESSES    40275
#define PHAPP_ID_TOOLS_STARTTASKMANAGER       40277
#define PHAPP_ID_COMPUTER_SHUTDOWNHYBRID      40278
#define PHAPP_ID_COMPUTER_RESTARTBOOTOPTIONS  40280
#define PHAPP_ID_HANDLE_OBJECTPROPERTIES1     40282
#define PHAPP_ID_HANDLE_OBJECTPROPERTIES2     40283
#define PHAPP_ID_OBJECT_GOTOOWNINGPROCESS     40284
#define PHAPP_ID_NETWORK_GOTOSERVICE          40285
#define PHAPP_ID_SERVICE_OPENFILELOCATION     40286
#define PHAPP_ID_PROCESS_GOTOPROCESS          40287
#define PHAPP_ID_MINIINFO_REFRESH             40288
#define PHAPP_ID_MINIINFO_REFRESHAUTOMATICALLY 40289
#define PHAPP_ID_ENVIRONMENT_EDIT             40290
#define PHAPP_ID_ENVIRONMENT_COPY             40291
#define PHAPP_ID_ENVIRONMENT_DELETE           40292
#define PHAPP_IDDYNAMIC                       50000
#define PHAPP_IDPLUGINS                       55000

// Next default values for new objects
// 
#if 0
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         40293
#define _APS_NEXT_CONTROL_VALUE         1385
#define _APS_NEXT_SYMED_VALUE           169
#endif
#endif
